### ISSUE TITLE
[ISSUE] [Table View] Annual Buy

### ISSUE THREAD

**Issue by cobo2bofb** [pampeanodev/btcretirementcalc#12]
[ISSUE] [Table View]

Table View doesn't reflect the Annual Estimated Buy, no matter what amount of BTC you buy per year, the red line in the chart (see below example) remains constant and doens't move/grow:

<img width="1285" alt="image" src="https://github.com/pampeanodev/btcretirementcalc/assets/100138874/829e52ac-8b97-4276-96a3-02984152b20c">

**Action: Correct this issue to reflect the new amount of Bitcoin (yearly growing) in Table View.**

**Comment by pampeanodev** [comment]
@cobo2bofb The fact that you don't see any changes is due to the magnitude of one and the other scale. If you click on USD, you will see only the Bitcoin line in the chart, and therefore see the variations in the amount of BTC you hold and accumulate. Take into account that, after retirement, you don't buy Bitcoin any longer, so the line goes down until the end of the lifetime (you are spending your savings).

**Comment by cobo2bofb** [comment]
@pampeanodev now I see. The scale is huge and column Y of the chart is neither USD nor Bitcoin, is just a "neutral number" for both units of account.

We need to rethink this because at the end of the day, when both lines are shown, that seems to be an sterile comparison then.

I'll close this one because it is really not an issue/bug, but something that might be rethought perhaps.

**Comment by pampeanodev** [comment]
closing as dismissed.
